### PR TITLE
Add Python script to plot logs

### PR DESCRIPTION
**Pull request by casperboone**
By @azqa.

Adds script for plotting the logs generated by the fuzzer.

### CODE REVIEW

**Comment by avandeursen** [comment]
Would it be possible to move this python script to subfolder?

Would it be be possible to add some documentation strings about intended usage?

**Comment by mauricioaniche** [comment]
We should also add some sort of `requirements.txt` with the libraries used here. I'll improve this PR and make this Python script completely runnable.

**Comment by azqanadeem** [comment]
The usage is rather simple: `python plotLogs.py <path/to/logs.txt>`. The logs are stored in `logs/` folder next to where the py script is. I suppose it would also need to be moved to a subfolder? In that case, you should update the path in `default-test/.../fuzzer/JPacmanFuzzer.java` .
The requirements for running the script are: `python2.7-dev` (including `setuptools`, `python-tk`) and `matplotlib`.

**Comment by mauricioaniche** [comment]
I moved the source code to a `ba` (_behavioral analysis_) folder and added a README there. 

I just tested and the script runs fine in both Python 2.7 and Python 3. I added a README.md with the dependencies, so students know what they might need to install.

If everybody is ok, I'll merge this PR.

**Comment by mauricioaniche** [comment]
As for future work: some comments in the Python scripts, so that students see what's going on there, would be nice (/cc @azqa)

**Comment by casperboone** [comment]
Cool! We could maybe just name the directory `behavioral-analysis` to make it more clear? Also, a `requirements.txt` would still be nice to have I think, but I'm also pretty ok with the readme already.

**Review by mauricioaniche — APPROVED** [review]
This looks good to me!

**Pull request merged**
